os: linux
dist: xenial
cache: yarn
language: node_js
node_js:
  - "11"
  - "10"
  - "8"
matrix:
  allow_failures:
    - node_js: "11"
  fast_finish: true
jobs:
  include:
    - stage: lint, test, and build
      name: lint
      script: npm run lint
      name: test
      script: npm test
      name: build
      script: npm run build
    - stage: publish
      script: true
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_KEY"
        skip_cleanup: true
        on:
          tags: true
          repo: AustinMatherne/pcf-services-parser
          node: "10"
