os: linux
dist: xenial
cache: yarn
language: node_js
node_js:
  - "11"
  - "10"
  - "8"
matrix:
  allow_failures:
    - node_js: "11"
  fast_finish: true
script:
  - yarn lint
  - yarn test --ci
  - yarn build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    node: "10"
    repo: AustinMatherne/pcf-services-parser
