os: linux
dist: xenial
cache: yarn
language: node_js
node_js:
  - "11"
branches:
  only:
    - master
install: yarn install --frozen-lockfile
script:
  - yarn commitlint-travis
  - yarn test --ci
  - yarn lint
  - yarn build
jobs:
  include:
    - stage: test
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      node_js: "10"
    - stage: test
      node_js: "8"
    - stage: release
      if: type == push
      script: skip
      deploy:
        provider: script
        script: yarn release
env:
  global:
    - secure: RnjyRIj5Ylujisff9EeNRZ+32PGeJoeIuuHxjs4kHPepkvB63Nkl8/mtr5eoVKPO7h9GsAv/tQyQhtl+AkKU8j0Ze8WVRtpwPoQxJV+0tTv/2tgJ0eXvP+mBqneVH+q2WXeQfH1LGVZVkdVhWQY3u/h9s7HI0wOu2sfn1zdjGp8Rz5/ptsO9Y87MzsfTNykCz2GtTVatveNrZjOo+1ed5R6G+RjzPHliFwrHWmj7SmmPqjK0VGz0Z1QLWxb9LMdUIu7iBCtsUsRdVdIOWZfUpteAGzHwoOA8H75Tsb5qd6it6tNAXjahpOpZG9NyMtjq4WzfTwAq1vs1exIIi8uDbPFHhM1+jPpvM+lqmfJiHxuERKv+UvDF1LdFejLzw8eQeak8w8K47VrD7T6UrvrLBr9rCs6v7BTVtC4XZHw+mER87kEbA2st3tY0Ya8c8wKGyb610g6ZwYjnw55aKYJ9qAatcYHPxfao1DvI5o1mBNc7IvnDCY9IiT5XrInzUTeylwFzI006S070kx9U1uurDuj5oedLO42vzPLyAA0h8//8T3JWaHmaRHwRGq04qzp20kDFBcknBIDGWOULnR1egz03nXiOJdBW5mv9UT1QcnZU6kL/Q3Yk/2+YXeFSrrWYWYqzQbrmNM5Egyuro2l4Z00Z49e8xiB1wjRjS5+lM6Q=
    - secure: LThJX0DU3XXa3YnsNSu0jsPNSi3Pmmji4Nh4ZllT5md9Bcv2XGK0dT4ynJvBJoXcWsZMrvmBu5Yym5fIsH2kcllU2cytQ67dQzrb8t5RB9skLpF4N9S9hjUWqtnxPxFUIEUemGEpj1uTl9lfHraF8gihTph+Oc1MbeeXst3LqRQGmyi50hwaFb4sWGH1W0iwIGE6f3jz38liVvh/qUWB8dN0lkJ9TgXVr72m1ckre+HMF/0xmkV0ZaNK1She6+F9dZM3s6An90oOTxkehAjBW/3j0UMCOlFFd/DFyROcRtTi2Mn8JeLIQwycIEqLuh7QPR2HpGiq2OMXio8ugGBwbFIVdBb40Wh2+Gwd5hsjO6pCiCso4lW0bb3vRGJ3R9HIEwXaiseZH6xlt95BeAs03Kd+m86QVdCeyG2hdrS1IahFFFZrJJ8fdAeUDvZW18riee9tJo288t0bEfTsi35mnEQLWfpCkEonGWy56UU9PBsWqBG16q380kW1p4tMVSAt+BMRxBUYFStZeS12sHikJXnZE0QUOFy+hlbAW3G7PxARS5Y+YKBrjBdkJvUQCQIuyOfpULxAgRtvXybsSAa47wGJKDT8MpsXGGTFt8WyqRmbKQ8msUaVztIk3c/hcGvCKiKKeu8I5XUVfGMoar7CrlZL4DdU2D5qLhb2S7kzUP4=
    - secure: YH2r80if3lfHQ9capOW8a6FwQIBc6ejoZVDYsABJifC7gYQOkiYlQ6uwLZrafBx12mMcMtrCOxqQUqTgxAvyb1x7x9hIUSiKdGom88QU+xjuYlBIczsUIfAX0wu41oWikF4URCM0Sbc1WjoHEfEzytlwetyL05Qg59a2H57zWdFAyaZ1ka9t2OHteMDQ/VCFMKy/KD2T8Y9OApCEY0HX7FzuNCwc0pGElTs73FtslRyMMWhX6qP5s+UgDs/Nb1vA0KJqNs7Da4qbLWdyNK54rRcruPa6BEM8WB+byyV3nRQhTwM26jdw+khw8yngiYJ/7GXj3srew+EL2MyFbUp+59HY8fA7uqgkRK48w52aErGtYb3Yb0X+fJgGyz5W4EeHWQSuaJyTa2IXYLe1sS63MkTV7J7iiAhY95aPDcZl4ZaobrU06fk6uoCOMs1ImBD9TEWJjNQTg38uZs+dJdFyyivq1nRKEr617mulMAMe/PBXKUi08SdltEEU9UEcy1blo+cuPA/lkiCQP/dQ70foE+DN+l4KG20yehiECPSoM4/ICdlNQTUotz3GSqpzZPl2fdmY7CZQe7G6HneaajK42p9sXKcmUjxP+LcXyESVEL1dQOTyCLwMi5XLXEdjZ1NdNjnj6d+No3nTDPNYuCDsz8VO0tWLovLd0/w2kL4qdbo=
