os: linux
dist: xenial
cache: yarn
language: node_js
addons:
  sonarcloud:
    organization: "austinmatherne-github"
node_js:
  - "11"
  - "10"
  - "8"
install: yarn install --frozen-lockfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - commitlint-travis
  - yarn test --ci
  - yarn lint --format json --out ./coverage/tslint-report.json
  - yarn build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage"
  - sonar-scanner
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    node: "11"
