os: linux
dist: xenial
cache: yarn
language: node_js
node_js:
  - "11"
  - "10"
  - "8"
install: yarn
script:
  - commitlint-travis
  - yarn lint
  - yarn test --ci
  - yarn build
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    node: "11"
