os: linux
dist: xenial
cache: yarn
language: node_js
addons:
  sonarcloud:
    organization: "austinmatherne-github"
node_js:
  - "11"
  - "10"
  - "8"
branches:
  only:
    - master
install: yarn install --frozen-lockfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn commitlint-travis
  - yarn test --ci
  - yarn lint --format json --out ./coverage/tslint-report.json
  - yarn build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - sonar-scanner
jobs:
  include:
    - stage: release
      if: type == push
      script: skip
      deploy:
        provider: script
        script: yarn release
